### ISSUE TITLE
All menu item texts became blured in Dark mode

### ISSUE THREAD

**Issue by NiceFeather** [windviki/vBookmarks#13]
All menu item texts became blured in Dark mode after Chrome update to 78, please fix this issue, thanks.

**Comment by windviki** [comment]
Sorry for the late response. What the OS is and what the dark mode is? I'm not sure Chrome has its dark mode (a dark theme?) so it may be OS-related problem.

**Comment by NiceFeather** [comment]
Yes, from Chrome 78 Experiments at chrome://flags/, you can search 'Force Dark Mode for Web Contents' at chrome://flags/#enable-force-dark to get the Dark Modes, all of Dark modes is indenpendent with OS. @windviki

**Comment by windviki** [comment]
Yes I reproduced it. 

This a CSS text-shadow issue.

When you're in light mode, the default CSS is 

`#results,
#tree {
    background-color: #f8f9fa;
    overflow: auto;
    outline: 0;
    padding: 3px 0;
    -webkit-box-shadow: inset 0 4px 4px -4px rgba(0, 0, 0, .1);
    -webkit-box-flex: 1;
    box-flex: 1;
    text-shadow: 0 1px #f6f6f6;
    position: relative;
}`

Notice the text-shadow value.

In dark mode, this shadow makes text "blurred".

If you change the color in "Custom CSS" which is in advanced settings of vbookmarks, you can make it clear.

e.g.

`#results,
#tree {
    background-color: #f8f9fa;
    overflow: auto;
    outline: 0;
    padding: 3px 0;
    -webkit-box-shadow: inset 0 4px 4px -4px rgba(0, 0, 0, .1);
    -webkit-box-flex: 1;
    box-flex: 1;
    text-shadow: 0 1px #000000;
    position: relative;
}`

But I cannot find a color that is suitable for both light and dark mode.

Even if I remove the text-shadow style, the "blur" occurred.

So I suggest you to custom the CSS like the example above by yourself since the dark mode is still an experiment option.

If there's a better solution, welcome to reopen this issue.
