### ISSUE TITLE
全览展开页

### ISSUE THREAD

**Issue by catshitz** [windviki/vBookmarks#28]
很好用，感谢大佬点个赞👍！
就是开页宽高限制太小，而且只能滚轮单列，不够直观。请问可以做成类似cent的这种 点击后直接单页+多列展示所有书签的样式吗？
这样效果最好最直观，也可以直接于展开页进行拖动、换排序等直观操作。
![image](https://user-images.githubusercontent.com/18102209/225513355-9071a562-ce7e-4dca-85dd-cf50366cf3ee.png)

**Comment by windviki** [comment]
非常感谢你的建议。这个项目已经存在了十多年，因为我自己的空闲时间有限，我只能保证它跟上Chrome更新，不影响大家平时使用。所以，目前没打算加入新功能。书签数据是Chrome和其他扩展共享的。因此，用Chrome自带的书签管理器，或者同时使用其他拥有不错的书签管理能力的扩展会是更好的选择。

Thanks a lot for your awesome suggestion. This project's been going for more than a decade, and with the little free time I've got, all I can do is make sure it keeps working smoothly with Chrome updates, without messing up your daily browsing. So, adding new features isn't on the agenda at the moment. Since bookmark data is shared between Chrome itself and other extensions, sticking to Chrome's built-in bookmark manager or using another extension that's really good at handling bookmarks would be the way to go.
